test: edits to test PRs
theteamworks/project-board-automation pull request #32
Opened 2022-05-31 19:20 UTC by gordsport

close #3

2022-05-31 19:54 UTC, gordsport-test commented on README.md
> +Blocks need text between them.
Non-blocking - update this

2022-05-31 20:07 UTC, gordsport-test commented on .github/workflows/project_board_automation.yml
> +  pull_request_review_comment:
non blocking - random comment

2022-05-31 22:24 UTC, gordsport-dev approved these changes

2022-06-01 09:11 UTC, gordsport-test requested changes

2022-06-01 19:59 UTC, merged